config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

class ActionDispatch::Routing::Mapper
  def front_draw(template)
    instance_eval(File.read(Rails.root.join("app/templates/front/#{template}/routes.rb")))
  end

  def back_draw(template)
    instance_eval(File.read(Rails.root.join("app/templates/back/#{template}/routes.rb")))
  end
end

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => redirect('/dashboard')
  get '/front/notifications/', controller: 'front/index', action: 'notifications'

  wash_out :dematbox

  devise_for :users

  authenticate :user, lambda { |u| u.is_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### ------------------------ front ---------------------------- ###
  get '/', to: redirect('/dashboard')
  front_draw('dashboard')
  front_draw('documentations')
  front_draw('notifications')
  front_draw('news')
  front_draw('account_number_rules')
  front_draw('account_sharings')
  front_draw('addresses')
  front_draw('bank_accounts')
  front_draw('bank_settings')
  front_draw('profiles')
  front_draw('collaborators')
  front_draw('compta_analytics')
  front_draw('exercises')
  front_draw('setups')
  front_draw('orders')
  front_draw('file_naming_policies')
  front_draw('knowings')
  front_draw('invoices')
  front_draw('reminder_emails')
  front_draw('file_sending_kits')
  front_draw('groups')
  front_draw('paper_set_orders')
  front_draw('journals')
  front_draw('ibiza')
  front_draw('my_company_files')
  front_draw('pack_reports')
  front_draw('accounting_plans')
  front_draw('vat_accounts')
  front_draw('csv_descriptors')
  front_draw('subscriptions')
  front_draw('group_organizations')
  front_draw('organizations')
  front_draw('preseizures')
  front_draw('documents')
  front_draw('documents_reloaded')
  front_draw('my_documents')
  front_draw('pieces_errors')
  front_draw('organizations')
  front_draw('reporting')
  front_draw('customers')
  front_draw('periods')
  front_draw('boxes')
  front_draw('external_file_storages')
  front_draw('ftps_setting')
  front_draw('payments')
  front_draw('compositions')
  front_draw('dematboxes')
  front_draw('retrievers')
  front_draw('retrieved_datas')
  front_draw('retrieved_datas_v2')
  front_draw('retriever_parameters')
  front_draw('exact_online')
  front_draw('paper_processes')
  front_draw('suspended')
  front_draw('profiles')
  front_draw('software_setting')
  front_draw('export_preseizures')

  ### --------------------------- admin ---------------------------- ###

  get 'admin/', to: redirect('/admin/dashboard')
  back_draw('dashboard')
  back_draw('reporting')
  back_draw('organizations')
  back_draw('process_reporting')
  back_draw('invoices')
  back_draw('users')
  back_draw('subscription_options')
  back_draw('subscriptions')
  back_draw('mobile_reporting')
  back_draw('orders')
  back_draw('events')
  back_draw('retrievers')
  back_draw('pre_assignment_deliveries')
  back_draw('dematboxes')
  back_draw('news')
  back_draw('emailed_documents')
  back_draw('cms_images')
  back_draw('scanning_providers')
  back_draw('account_sharings')
  back_draw('notifications')
  back_draw('pre_assignment_blocked_duplicates')
  back_draw('notification_settings')
  back_draw('job_processing')
  back_draw('counter_error_script_mailer')
  back_draw('budgea_retriever')
  back_draw('zoho_crms')
  back_draw('pkill')
  back_draw('reset')
  back_draw('package_setting')
  back_draw('tickets')
  back_draw('supports')

  #### -------------------------------- native resources -----------------------------###

  scope module: 'ppp' do
    resources :compta

    resources :kits, only: %w(index create)
    get 'kits/:year/:month/:day', controller: 'kits', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :receipts, only: %w(index create)
    get 'receipts/:year/:month/:day', controller: 'receipts', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :scans, only: %w(index create) do
      patch :add,       on: :member
      get   :cancel,    on: :collection
      patch :overwrite, on: :member
    end
    get 'scans/:year/:month/:day', controller: 'scans', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :returns, only: %w(index create)
    get 'returns/:year/:month/:day', controller: 'returns', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    scope '/scans' do
      resource :return_labels
    end
    post '/scans/return_labels/:year/:month/:day',     controller: 'return_labels', action: 'create'
    get  '/scans/return_labels/new/:year/:month/:day', controller: 'return_labels', action: 'new'

    get '/paper_set_orders', controller: 'paper_set_orders', action: 'index'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      resources :users, only: %w() do
        collection do
          get :jefacture
        end

        resources :accounting_plans,  only: %w(index)
        resources :account_book_types, only: %w(index)
      end

      resources :pieces,            only: %w(update)

      resources :operations,        only: %w(create) do
        get 'by_iban/:iban', action: 'index_by_iban', on: :collection
        post 'not_processed', action: 'not_processed', on: :collection
      end

      resources :temp_documents,    only: %w(create)

      resources :bank_accounts,     only: %w(index) do
        member do
          get :last_operation
        end
      end

      resources :neatops_specific, only: :create
    end

    namespace :v1 do
      resources :pre_assignments do
        post 'update_comment', on: :collection
      end

      resources :system, only: %w(index) do
        post 'my_customers', on: :collection
        post 'piece_url', on: :collection
      end
    end

    namespace :mobile do
      devise_for :users

      resources :remote_authentication do
        collection do
          post :request_connexion
          post :get_user_parameters
          post :ping
        end
      end

      resources :data_loader do
        collection do
          post :load_customers
          post :load_user_organizations
          post :load_packs
          post :load_documents_processed
          post :load_documents_processing
          post :load_stats
          post :load_preseizures
          post :get_packs
          post :get_reports
          get  :render_image_documents
        end
      end

      resources :preseizures do
        collection do
          post :get_details
          post :deliver
          post :edit_preseizures
          post :edit_account
          post :edit_entry
        end
      end

      resources :operations do
        collection do
          post :get_operations
          post :force_pre_assignment
          post :get_customers_options
        end
      end

      resources :account_sharing do
        collection do
          post :load_shared_docs
          post :load_shared_contacts

          post :get_list_collaborators
          post :get_list_customers
          post :add_shared_docs
          post :add_shared_contacts
          post :edit_shared_contacts
          post :accept_shared_docs
          post :delete_shared_docs
          post :delete_shared_contacts

          post :load_shared_docs_customers
          post :add_shared_docs_customers
          post :add_sharing_request_customers
        end
      end

      resources :file_uploader do
        post 'load_file_upload_params', on: :collection
        post 'load_file_upload_users', on: :collection
        post 'load_user_analytics', on: :collection
        post 'set_pieces_analytics', on: :collection
      end

      resources :firebase_notification do
        collection do
          post :get_notifications
          post :release_new_notifications
          post :register_firebase_token
        end
      end

      resources :error_report do
        post 'send_error_report', on: :collection
      end
    end

    namespace :sgi do
      namespace :v1 do
        resources :grouping do
          get 'bundle_needed/:delivery_type', action: 'bundle_needed',  on: :collection
          post 'bundled', on: :collection
        end

        resources :preassignment do
          get 'preassignment_needed/:compta_type', action: 'preassignment_needed', on: :collection
          get 'download_piece', on: :collection
          post 'push_preassignment/:piece_id', action: 'push_preassignment', on: :collection
          post 'update_teeo_pieces', action: 'update_teeo_pieces', on: :collection
        end

        resources :mapping_generator do
          get 'get_json', on: :collection
        end

        resources :jefacture do
          get 'waiting_validation',  on: :collection
          post 'pre_assigned',       on: :collection
        end
      end
    end
  end

  match '*a', to: 'errors#routing', via: :all
end

app/controllers/ppp/compta_controller.rb
# frozen_string_literal: true

class Ppp::ComptaController < ApplicationController
  before_action :authenticate
  before_action :load_users

  # GET /compta
  def index; end

  # GET /compta/:user_id
  def show
    @user = @users.find_by_code params[:id]
  end

  private

  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      compta_operators = [{ "username": 'gabriel', "password": 'C0wbjA78' }, { "username": 'ft', "password": 'idocompta' }]
      compta_operators.select do |_operator|
        name == 'gabriel' && password == 'C0wbjA78'
      end.first.present?
    end
  end

  def load_users
    organization_ids = Organization.active.pluck(:id)

    user_ids = AccountBookType.where.not(user_id: nil).compta_processable.distinct.pluck(:user_id)

    @users = User.where(organization_id: organization_ids, id: user_ids).active.includes(:options)
  end
end

app/controllers/ppp/kits_controller.rb
# frozen_string_literal: true

class Ppp::KitsController < PaperProcessesController
  # GET /kits
  def index
    paper_processes = PaperProcess.kits.where('created_at >= ? AND created_at <= ?', @current_time.beginning_of_month, @current_time.end_of_month)

    respond_to do |format|
      format.html do
        @grouped_paper_processes = paper_processes.order(created_at: :desc).group_by { |e| e.created_at.day }

        @paper_process = PaperProcess.where(id: session[:kit_paper_process_id]).first

        @paper_process ||= PaperProcess.new journals_count: 0, periods_count: 0
      end
      format.csv do
        send_data(PaperProcess.to_csv(paper_processes.order(created_at: :asc)), type: 'text/csv', filename: "kits_#{@current_time.strftime('%Y_%m')}.csv")
      end
    end
  end

  # POST /kits
  def create
    _params = paper_process_params

    _params[:customer_code] = CustomUtils.replace_code_of(_params[:customer_code])

    @paper_process = PaperProcess.where(type: 'kit', tracking_number: _params[:tracking_number]).first

    @paper_process ||= PaperProcess.new(type: 'kit')

    @paper_process.assign_attributes(_params)

    if @paper_process.persisted? && @paper_process.valid?
      session[:kit_paper_process_id] = nil

      @paper_process.save

      flash[:success] = 'Modifié avec succès.'
    elsif @paper_process.save
      session[:kit_paper_process_id] = nil

      @paper_process.user         = User.find_by_code @paper_process.customer_code
      @paper_process.organization = @paper_process.user.try(:organization)

      @paper_process.save

      flash[:success] = 'Créé avec succès.'
    else
      session[:kit_paper_process_id] = @paper_process.id
      flash[:error]               = 'Donnée(s) invalide(s).'
    end

    redirect_to kits_path
  end

  private

  def paper_process_params
    params.require(:paper_process).permit(
      :tracking_number,
      :customer_code,
      :journals_count,
      :periods_count,
      :order_id
    )
  end
end

app/controllers/ppp/paper_set_orders_controller.rb
# frozen_string_literal: true

class Ppp::PaperSetOrdersController < PaperProcessesController
  # GET /paper_set_orders
  def index
    @orders = Order.paper_sets.where.not(organization_id: [169, 7]).billed #Where oganization not Censial and Idocus
    @orders = Order.search_for_collection(@orders, search_terms(params[:order_contains]))
    @orders_count = @orders.count
    @orders = @orders.joins(:user).select('orders.*, users.code as user_code, users.company as company, users.id as user_id').order("#{sort_column} #{sort_direction}").page(params[:page]).per(params[:per_page])
  end

  private

  def sort_column
    if params[:sort].in? %w[created_at id user_code state]
      params[:sort]
    else
      'created_at'
    end
  end
  helper_method :sort_column

  def sort_direction
    if params[:direction].in? %w[asc desc]
      params[:direction]
    else
      'desc'
    end
  end
  helper_method :sort_direction
end

app/controllers/ppp/receipts_controller.rb
# frozen_string_literal: true

class Ppp::ReceiptsController < PaperProcessesController
  def index
    paper_processes = PaperProcess.receipts.where('created_at >= ? AND created_at <= ?', @current_time.beginning_of_month, @current_time.end_of_month)

    respond_to do |format|
      format.html do
        @grouped_paper_processes = paper_processes.order(created_at: :desc).group_by { |e| e.created_at.day }
        @paper_process = PaperProcess.where(id: session[:receipt_paper_process_id]).first
        @paper_process ||= PaperProcess.new
      end
      format.csv do
        send_data(PaperProcess.to_csv(paper_processes.order(created_at: :asc)), type: 'text/csv', filename: "receipts_#{@current_time.strftime('%Y_%m')}.csv")
      end
    end
  end

  def create
    _params = paper_process_params

    _params[:customer_code] = CustomUtils.replace_code_of(_params[:customer_code])

    user = User.get_by_code(_params[:customer_code])
    if user
      @paper_process   = PaperProcess.where(type: 'receipt', tracking_number: _params[:tracking_number]).first
      @paper_process ||= PaperProcess.new(type: 'receipt')
      @paper_process.assign_attributes(_params)
      if @paper_process.persisted? && @paper_process.valid?
        session[:receipt_paper_process_id] = nil
        @paper_process.save
        flash[:success] = 'Modifié avec succès.'
      elsif @paper_process.save
        session[:receipt_paper_process_id] = nil
        @paper_process.user         = user
        @paper_process.organization = user.organization
        @paper_process.save
        flash[:success] = 'Créé avec succès.'
      else
        session[:receipt_paper_process_id] = @paper_process.id
        flash[:error] = 'Donnée(s) invalide(s).'
      end
    else
      paper_process   = PaperProcess.where(type: 'receipt', tracking_number: _params[:tracking_number]).first
      paper_process ||= PaperProcess.new(type: 'receipt')
      paper_process.assign_attributes(_params)
      paper_process.valid?
      session[:receipt_paper_process_id] = paper_process.id
      flash[:error] = 'Donnée(s) invalide(s).'
    end
    redirect_to receipts_path
  end

  private

  def paper_process_params
    params.require(:paper_process).permit(:tracking_number, :customer_code)
  end
end

app/controllers/ppp/return_labels_controller.rb
# frozen_string_literal: true

class Ppp::ReturnLabelsController < PaperProcessesController
  layout false

  # GET /scans/return_labels
  def show
    filepath = ReturnLabels::FILE_PATH

    if File.exist?(filepath)
      filename = File.basename(filepath)

      file = File.open(filepath, "rb")
      contents = file.read
      file.close

      send_data(contents, type: 'application/pdf', filename: filename, x_sendfile: true, disposition: 'inline')
    else
      render body: nil, status: 404
    end
  end

  # GET /scans/return_labels/new
  def new
    # @scanned_by = @user.scanning_provider.name if @user || nil 'ppp'
    @scanned_by = 'ppp'

    @return_labels = ReturnLabels.new(scanned_by: @scanned_by, time: @current_time)

    @customers = @return_labels.users.sort_by do |e|
      (e.is_return_label_generated_today? ? '1_' : '0_') + e.code
    end
  end

  # POST /scans/return_labels
  def create
    if params[:return_labels] && params[:return_labels][:customers]
      @return_labels = ReturnLabels.new(params[:return_labels].merge(time: @current_time))
      @return_labels.render_pdf
    end
    redirect_to '/scans/return_labels'
  end
end

app/helpers/layouts_helper.rb
# -*- encoding : UTF-8 -*-
# FIXME : whole check

module LayoutsHelper
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of front/layouts/child.html.haml, include this:
  #
  # <% parent_layout "parent" %>
  #

  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "front/layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/ppp/_footer.html.haml
.modal.fade.in#all_notifications{'aria-hidden' => 'true', :role => 'dialog', :tabindex => '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title.bold Notifications 
        %button.btn-close{'aria-label' => 'Close', 'data-bs-dismiss' => 'modal', :type => 'button'}
      .modal-body.no-padding

%footer.navbar-fixed-bottom.p-3.main_footer
  .row
    .col-md-6.text-start.text-white
      .contact-number
        .client-contact.d-inline
          %span.semibold.mt-2.d-inline  Support Client :
          .number.d-inline
            = image_tag('application/contact_number.png', alt: 'contact', class: 'contact_number')
            %span.open-time.semibold 8h à 12h - 13h à 17h
    .col-md-3.text-start
      %p.m-0.text-white
        = t('footer.copyright_text')
        &copy;
        %span.semibold= Time.now.strftime('%Y')
    .col-md-3.network-link
      %p.m-0.text-center.text-white
        %a.facebook.ms-4{ href: 'https://www.facebook.com/idocus/', target: '_blank' }
          %svg{:fill => "none", :height => "16", :viewbox => "0 0 9 16", :width => "9", :xmlns => "http://www.w3.org/2000/svg"}
            %path{"clip-rule" => "evenodd", :d => "M5.73256 3.86286C5.73256 3.14286 5.80456 2.75771 6.89256 2.75771H8.34742V0H6.01942C3.22513 0 2.23999 1.33829 2.23999 3.58743V5.24229H0.497131V8H2.23999V16H5.72799V8H8.05485L8.36342 5.24229H5.72799L5.73256 3.86286Z", :fill => "white", "fill-rule" => "evenodd"}
        %a.twitter.ms-4{ href: 'https://twitter.com/idocus', target: '_blank' }
          %svg{:fill => "none", :height => "14", :viewbox => "0 0 16 14", :width => "16", :xmlns => "http://www.w3.org/2000/svg"}
            %path{"clip-rule" => "evenodd", :d => "M15.5577 0.909726C14.9113 1.28325 14.2066 1.5452 13.4731 1.68458C13.1617 1.36349 12.7886 1.10875 12.3761 0.935715C11.9636 0.762676 11.5204 0.674918 11.0731 0.677726C10.2155 0.666738 9.38859 0.99662 8.77401 1.59491C8.15944 2.1932 7.80747 3.01097 7.79543 3.86858C7.79651 4.1151 7.82682 4.36063 7.88571 4.60001C6.5877 4.54128 5.31592 4.21434 4.1505 3.63979C2.98509 3.06525 1.9513 2.25555 1.11429 1.26173C0.823959 1.74497 0.670302 2.29798 0.669714 2.86173C0.67073 3.39206 0.805013 3.91364 1.06023 4.37854C1.31544 4.84343 1.68339 5.23673 2.13029 5.5223C1.61071 5.50711 1.1019 5.37052 0.644571 5.12344C0.644571 5.13601 0.644571 5.14973 0.644571 5.16344C0.652124 5.90897 0.918381 6.62873 1.39783 7.19969C1.87728 7.77065 2.54015 8.15736 3.27314 8.29373C2.99095 8.36924 2.70012 8.40766 2.408 8.40801C2.20089 8.40842 1.99423 8.3889 1.79086 8.34973C2.00993 8.991 2.42246 9.54858 2.97161 9.94565C3.52075 10.3427 4.17951 10.5598 4.85714 10.5669C3.68599 11.4597 2.25324 11.9417 0.780572 11.9383C0.519609 11.9362 0.258987 11.919 0 11.8869C1.50843 12.8274 3.25094 13.3248 5.02857 13.3223C6.24068 13.3484 7.44588 13.1331 8.57402 12.6891C9.70217 12.245 10.7307 11.581 11.5998 10.7357C12.469 9.89044 13.1613 8.88073 13.6365 7.76536C14.1117 6.64999 14.3604 5.45124 14.368 4.23887C14.368 4.10058 14.368 3.96344 14.3589 3.8263C15.0001 3.3773 15.5559 2.81725 16 2.17258C15.3996 2.43243 14.7642 2.60226 14.1143 2.67658C14.7954 2.28407 15.309 1.65544 15.5577 0.909726Z", :fill => "white", "fill-rule" => "evenodd"}
        %a.linkedin.ms-4{ href: 'https://www.linkedin.com/company/idocus', target: '_blank' }
          %svg{:fill => "none", :height => "16", :viewbox => "0 0 16 16", :width => "16", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "M8.97828 5.52455V6.95312C9.07771 6.82055 9.16114 6.70397 9.25142 6.59197C9.61264 6.1319 10.084 5.7703 10.6219 5.54058C11.1599 5.31087 11.747 5.22045 12.3291 5.27769C12.9512 5.29883 13.5583 5.47397 14.096 5.7874C14.5197 6.04586 14.8867 6.38754 15.1746 6.79179C15.4626 7.19605 15.6656 7.65448 15.7714 8.1394C15.905 8.67345 15.9714 9.22206 15.9691 9.77255C15.9691 11.7337 15.9691 13.6952 15.9691 15.6571C15.9691 15.6891 15.9691 15.7223 15.9691 15.76H12.5714V15.6571C12.5714 13.8285 12.5714 12 12.5714 10.1714C12.5786 9.76609 12.5116 9.36288 12.3737 8.98169C12.2739 8.6893 12.0854 8.43529 11.8345 8.25504C11.5835 8.07478 11.2827 7.97723 10.9737 7.97597C10.717 7.96584 10.4608 8.00753 10.2205 8.09855C9.98025 8.18958 9.76076 8.32807 9.57517 8.50577C9.38958 8.68347 9.24169 8.89673 9.14031 9.13283C9.03894 9.36893 8.98617 9.62303 8.98514 9.87998C8.99428 10.6228 8.98514 11.3657 8.98514 12.1063C8.98514 13.2895 8.98514 14.4724 8.98514 15.6548V15.7623H5.58057V5.52455H8.97828Z", :fill => "white"}
            %path{:d => "M0.0297241 5.52228H3.42858V15.76H0.0297241V5.52228Z", :fill => "white"}
            %path{:d => "M1.72685 3.74399C2.69446 3.74399 3.47885 2.95959 3.47885 1.99199C3.47885 1.02439 2.69446 0.23999 1.72685 0.23999C0.759251 0.23999 -0.0251465 1.02439 -0.0251465 1.99199C-0.0251465 2.95959 0.759251 3.74399 1.72685 3.74399Z", :fill => "white"}

app/views/layouts/ppp/paper_process.html.haml
!!!
%html
  %head
    %title Idocus | Traitements papiers
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-type' }
    %link{ rel: 'shortcut icon', type: 'image/ico', href: image_path('favicon.ico') }    
    %link{ :rel => 'shortcut icon', :type => "image/ico", :href => image_path('favicon.ico') }
    = stylesheet_link_tag 'front/main'
    = javascript_include_tag 'front/main'
  %body
    #wrap.extern
      %nav.navbar.navbar-expand-lg.fixed-top.sticky-top.main_menu.no-padding
        .row.w-100.no-margin
          .col-md-1.text-center
            = link_to image_tag('logo/tiny_logo_2.png', alt: 'logo iDocus'), root_path, class: 'navbar-brand no-margin', data:{ href: '/' }
          .col-md-6.menu
            %ul.navbar-nav
              %li.nav-item{ class: ('active' if controller_name == 'paper_set_orders') }
                = link_to 'Commandes', paper_set_orders_path, class: 'nav-link bold'
              %li.nav-item{ class: ('active' if controller_name == 'kits') }
                = link_to 'Kit', kits_path, class: 'nav-link bold'
              %li.nav-item{ class: ('active' if controller_name == 'receipts') }
                = link_to 'Réception', receipts_path, class: 'nav-link bold'
              %li.nav-item{ class: ('active' if controller_name == 'scans') }
                = link_to 'Numérisation', scans_path, class: 'nav-link bold'
              %li.nav-item{ class: ('active' if controller_name == 'returns') }
                = link_to 'Retour', returns_path, class: 'nav-link bold'
          - if current_user
            .col-md-5.text-end.user-action
              %span.text-grey.semibold Connecté en tant que
              %span= link_to current_user.email, root_path, class: 'green-label semibold'
              %span &#124;
              %span= link_to 'déconnexion', destroy_user_session_path, method: :delete, class: 'red-label semibold'
    #next-nav-wrapper
    .body_content.no-margin
      .container-fluid= yield
    #push

    .loading_box.hide
      .box.text-center
        %img{ src: '/assets/application/spinner_gray_alpha.gif', alt: 'spin gif'}
        %label.mt-2.semibold Chargement

    .scroll-on-top.pointer.hide
      .scroll-arrow= glyphicon('arrow-top', { size: '16', color: 'rgba(26, 26, 26, 0.7)' })
    = render partial: 'layouts/ppp/footer'

    = render partial: 'layouts/notice_flush_messages'
    = render '/shared/google_analytics'
  = javascript_include_tag 'ppp/paper_process'