config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

class ActionDispatch::Routing::Mapper
  def front_draw(template)
    instance_eval(File.read(Rails.root.join("app/templates/front/#{template}/routes.rb")))
  end

  def back_draw(template)
    instance_eval(File.read(Rails.root.join("app/templates/back/#{template}/routes.rb")))
  end
end

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => redirect('/dashboard')
  get '/front/notifications/', controller: 'front/index', action: 'notifications'

  wash_out :dematbox

  devise_for :users

  authenticate :user, lambda { |u| u.is_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### ------------------------ front ---------------------------- ###
  get '/', to: redirect('/dashboard')
  front_draw('dashboard')
  front_draw('documentations')
  front_draw('notifications')
  front_draw('news')
  front_draw('account_number_rules')
  front_draw('account_sharings')
  front_draw('addresses')
  front_draw('bank_accounts')
  front_draw('bank_settings')
  front_draw('profiles')
  front_draw('collaborators')
  front_draw('compta_analytics')
  front_draw('exercises')
  front_draw('setups')
  front_draw('orders')
  front_draw('file_naming_policies')
  front_draw('knowings')
  front_draw('invoices')
  front_draw('reminder_emails')
  front_draw('file_sending_kits')
  front_draw('groups')
  front_draw('paper_set_orders')
  front_draw('journals')
  front_draw('ibiza')
  front_draw('my_company_files')
  front_draw('pack_reports')
  front_draw('accounting_plans')
  front_draw('vat_accounts')
  front_draw('csv_descriptors')
  front_draw('subscriptions')
  front_draw('group_organizations')
  front_draw('organizations')
  front_draw('preseizures')
  front_draw('documents')
  front_draw('documents_reloaded')
  front_draw('my_documents')
  front_draw('pieces_errors')
  front_draw('organizations')
  front_draw('reporting')
  front_draw('customers')
  front_draw('periods')
  front_draw('boxes')
  front_draw('external_file_storages')
  front_draw('ftps_setting')
  front_draw('payments')
  front_draw('compositions')
  front_draw('dematboxes')
  front_draw('retrievers')
  front_draw('retrieved_datas')
  front_draw('retrieved_datas_v2')
  front_draw('retriever_parameters')
  front_draw('exact_online')
  front_draw('paper_processes')
  front_draw('suspended')
  front_draw('profiles')
  front_draw('software_setting')
  front_draw('export_preseizures')

  ### --------------------------- admin ---------------------------- ###

  get 'admin/', to: redirect('/admin/dashboard')
  back_draw('dashboard')
  back_draw('reporting')
  back_draw('organizations')
  back_draw('process_reporting')
  back_draw('invoices')
  back_draw('users')
  back_draw('subscription_options')
  back_draw('subscriptions')
  back_draw('mobile_reporting')
  back_draw('orders')
  back_draw('events')
  back_draw('retrievers')
  back_draw('pre_assignment_deliveries')
  back_draw('dematboxes')
  back_draw('news')
  back_draw('emailed_documents')
  back_draw('cms_images')
  back_draw('scanning_providers')
  back_draw('account_sharings')
  back_draw('notifications')
  back_draw('pre_assignment_blocked_duplicates')
  back_draw('notification_settings')
  back_draw('job_processing')
  back_draw('counter_error_script_mailer')
  back_draw('budgea_retriever')
  back_draw('zoho_crms')
  back_draw('pkill')
  back_draw('reset')
  back_draw('package_setting')
  back_draw('tickets')
  back_draw('supports')

  #### -------------------------------- native resources -----------------------------###

  scope module: 'ppp' do
    resources :compta

    resources :kits, only: %w(index create)
    get 'kits/:year/:month/:day', controller: 'kits', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :receipts, only: %w(index create)
    get 'receipts/:year/:month/:day', controller: 'receipts', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :scans, only: %w(index create) do
      patch :add,       on: :member
      get   :cancel,    on: :collection
      patch :overwrite, on: :member
    end
    get 'scans/:year/:month/:day', controller: 'scans', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :returns, only: %w(index create)
    get 'returns/:year/:month/:day', controller: 'returns', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    scope '/scans' do
      resource :return_labels
    end
    post '/scans/return_labels/:year/:month/:day',     controller: 'return_labels', action: 'create'
    get  '/scans/return_labels/new/:year/:month/:day', controller: 'return_labels', action: 'new'

    get '/paper_set_orders', controller: 'paper_set_orders', action: 'index'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      resources :users, only: %w() do
        collection do
          get :jefacture
        end

        resources :accounting_plans,  only: %w(index)
        resources :account_book_types, only: %w(index)
      end

      resources :pieces,            only: %w(update)

      resources :operations,        only: %w(create) do
        get 'by_iban/:iban', action: 'index_by_iban', on: :collection
        post 'not_processed', action: 'not_processed', on: :collection
      end

      resources :temp_documents,    only: %w(create)

      resources :bank_accounts,     only: %w(index) do
        member do
          get :last_operation
        end
      end

      resources :neatops_specific, only: :create
    end

    namespace :v1 do
      resources :pre_assignments do
        post 'update_comment', on: :collection
      end

      resources :system, only: %w(index) do
        post 'my_customers', on: :collection
        post 'piece_url', on: :collection
      end
    end

    namespace :mobile do
      devise_for :users

      resources :remote_authentication do
        collection do
          post :request_connexion
          post :get_user_parameters
          post :ping
        end
      end

      resources :data_loader do
        collection do
          post :load_customers
          post :load_user_organizations
          post :load_packs
          post :load_documents_processed
          post :load_documents_processing
          post :load_stats
          post :load_preseizures
          post :get_packs
          post :get_reports
          get  :render_image_documents
        end
      end

      resources :preseizures do
        collection do
          post :get_details
          post :deliver
          post :edit_preseizures
          post :edit_account
          post :edit_entry
        end
      end

      resources :operations do
        collection do
          post :get_operations
          post :force_pre_assignment
          post :get_customers_options
        end
      end

      resources :account_sharing do
        collection do
          post :load_shared_docs
          post :load_shared_contacts

          post :get_list_collaborators
          post :get_list_customers
          post :add_shared_docs
          post :add_shared_contacts
          post :edit_shared_contacts
          post :accept_shared_docs
          post :delete_shared_docs
          post :delete_shared_contacts

          post :load_shared_docs_customers
          post :add_shared_docs_customers
          post :add_sharing_request_customers
        end
      end

      resources :file_uploader do
        post 'load_file_upload_params', on: :collection
        post 'load_file_upload_users', on: :collection
        post 'load_user_analytics', on: :collection
        post 'set_pieces_analytics', on: :collection
      end

      resources :firebase_notification do
        collection do
          post :get_notifications
          post :release_new_notifications
          post :register_firebase_token
        end
      end

      resources :error_report do
        post 'send_error_report', on: :collection
      end
    end

    namespace :sgi do
      namespace :v1 do
        resources :grouping do
          get 'bundle_needed/:delivery_type', action: 'bundle_needed',  on: :collection
          post 'bundled', on: :collection
        end

        resources :preassignment do
          get 'preassignment_needed/:compta_type', action: 'preassignment_needed', on: :collection
          get 'download_piece', on: :collection
          post 'push_preassignment/:piece_id', action: 'push_preassignment', on: :collection
          post 'update_teeo_pieces', action: 'update_teeo_pieces', on: :collection
        end

        resources :mapping_generator do
          get 'get_json', on: :collection
        end

        resources :jefacture do
          get 'waiting_validation',  on: :collection
          post 'pre_assigned',       on: :collection
        end
      end
    end
  end

  match '*a', to: 'errors#routing', via: :all
end

app/controllers/ppp/compta_controller.rb
# frozen_string_literal: true

class Ppp::ComptaController < ApplicationController
  before_action :authenticate
  before_action :load_users

  # GET /compta
  def index; end

  # GET /compta/:user_id
  def show
    @user = @users.find_by_code params[:id]
  end

  private

  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      compta_operators = [{ "username": 'gabriel', "password": 'C0wbjA78' }, { "username": 'ft', "password": 'idocompta' }]
      compta_operators.select do |_operator|
        name == 'gabriel' && password == 'C0wbjA78'
      end.first.present?
    end
  end

  def load_users
    organization_ids = Organization.active.pluck(:id)

    user_ids = AccountBookType.where.not(user_id: nil).compta_processable.distinct.pluck(:user_id)

    @users = User.where(organization_id: organization_ids, id: user_ids).active.includes(:options)
  end
end

app/controllers/ppp/kits_controller.rb
# frozen_string_literal: true

class Ppp::KitsController < PaperProcessesController
  # GET /kits
  def index
    paper_processes = PaperProcess.kits.where('created_at >= ? AND created_at <= ?', @current_time.beginning_of_month, @current_time.end_of_month)

    respond_to do |format|
      format.html do
        @grouped_paper_processes = paper_processes.order(created_at: :desc).group_by { |e| e.created_at.day }

        @paper_process = PaperProcess.where(id: session[:kit_paper_process_id]).first

        @paper_process ||= PaperProcess.new journals_count: 0, periods_count: 0
      end
      format.csv do
        send_data(PaperProcess.to_csv(paper_processes.order(created_at: :asc)), type: 'text/csv', filename: "kits_#{@current_time.strftime('%Y_%m')}.csv")
      end
    end
  end

  # POST /kits
  def create
    _params = paper_process_params

    _params[:customer_code] = CustomUtils.replace_code_of(_params[:customer_code])

    @paper_process = PaperProcess.where(type: 'kit', tracking_number: _params[:tracking_number]).first

    @paper_process ||= PaperProcess.new(type: 'kit')

    @paper_process.assign_attributes(_params)

    if @paper_process.persisted? && @paper_process.valid?
      session[:kit_paper_process_id] = nil

      @paper_process.save

      flash[:success] = 'Modifié avec succès.'
    elsif @paper_process.save
      session[:kit_paper_process_id] = nil

      @paper_process.user         = User.find_by_code @paper_process.customer_code
      @paper_process.organization = @paper_process.user.try(:organization)

      @paper_process.save

      flash[:success] = 'Créé avec succès.'
    else
      session[:kit_paper_process_id] = @paper_process.id
      flash[:error]               = 'Donnée(s) invalide(s).'
    end

    redirect_to kits_path
  end

  private

  def paper_process_params
    params.require(:paper_process).permit(
      :tracking_number,
      :customer_code,
      :journals_count,
      :periods_count,
      :order_id
    )
  end
end

app/controllers/ppp/paper_set_orders_controller.rb
# frozen_string_literal: true

class Ppp::PaperSetOrdersController < PaperProcessesController
  # GET /paper_set_orders
  def index
    @orders = Order.paper_sets.where.not(organization_id: [169, 7]).billed #Where oganization not Censial and Idocus
    @orders = Order.search_for_collection(@orders, search_terms(params[:order_contains]))
    @orders_count = @orders.count
    @orders = @orders.joins(:user).select('orders.*, users.code as user_code, users.company as company, users.id as user_id').order("#{sort_column} #{sort_direction}").page(params[:page]).per(params[:per_page])
  end

  private

  def sort_column
    if params[:sort].in? %w[created_at id user_code state]
      params[:sort]
    else
      'created_at'
    end
  end
  helper_method :sort_column

  def sort_direction
    if params[:direction].in? %w[asc desc]
      params[:direction]
    else
      'desc'
    end
  end
  helper_method :sort_direction
end

app/controllers/ppp/receipts_controller.rb
# frozen_string_literal: true

class Ppp::ReceiptsController < PaperProcessesController
  def index
    paper_processes = PaperProcess.receipts.where('created_at >= ? AND created_at <= ?', @current_time.beginning_of_month, @current_time.end_of_month)

    respond_to do |format|
      format.html do
        @grouped_paper_processes = paper_processes.order(created_at: :desc).group_by { |e| e.created_at.day }
        @paper_process = PaperProcess.where(id: session[:receipt_paper_process_id]).first
        @paper_process ||= PaperProcess.new
      end
      format.csv do
        send_data(PaperProcess.to_csv(paper_processes.order(created_at: :asc)), type: 'text/csv', filename: "receipts_#{@current_time.strftime('%Y_%m')}.csv")
      end
    end
  end

  def create
    _params = paper_process_params

    _params[:customer_code] = CustomUtils.replace_code_of(_params[:customer_code])

    user = User.get_by_code(_params[:customer_code])
    if user
      @paper_process   = PaperProcess.where(type: 'receipt', tracking_number: _params[:tracking_number]).first
      @paper_process ||= PaperProcess.new(type: 'receipt')
      @paper_process.assign_attributes(_params)
      if @paper_process.persisted? && @paper_process.valid?
        session[:receipt_paper_process_id] = nil
        @paper_process.save
        flash[:success] = 'Modifié avec succès.'
      elsif @paper_process.save
        session[:receipt_paper_process_id] = nil
        @paper_process.user         = user
        @paper_process.organization = user.organization
        @paper_process.save
        flash[:success] = 'Créé avec succès.'
      else
        session[:receipt_paper_process_id] = @paper_process.id
        flash[:error] = 'Donnée(s) invalide(s).'
      end
    else
      paper_process   = PaperProcess.where(type: 'receipt', tracking_number: _params[:tracking_number]).first
      paper_process ||= PaperProcess.new(type: 'receipt')
      paper_process.assign_attributes(_params)
      paper_process.valid?
      session[:receipt_paper_process_id] = paper_process.id
      flash[:error] = 'Donnée(s) invalide(s).'
    end
    redirect_to receipts_path
  end

  private

  def paper_process_params
    params.require(:paper_process).permit(:tracking_number, :customer_code)
  end
end

app/controllers/ppp/return_labels_controller.rb
# frozen_string_literal: true

class Ppp::ReturnLabelsController < PaperProcessesController
  layout false

  # GET /scans/return_labels
  def show
    filepath = ReturnLabels::FILE_PATH

    if File.exist?(filepath)
      filename = File.basename(filepath)

      file = File.open(filepath, "rb")
      contents = file.read
      file.close

      send_data(contents, type: 'application/pdf', filename: filename, x_sendfile: true, disposition: 'inline')
    else
      render body: nil, status: 404
    end
  end

  # GET /scans/return_labels/new
  def new
    # @scanned_by = @user.scanning_provider.name if @user || nil 'ppp'
    @scanned_by = 'ppp'

    @return_labels = ReturnLabels.new(scanned_by: @scanned_by, time: @current_time)

    @customers = @return_labels.users.sort_by do |e|
      (e.is_return_label_generated_today? ? '1_' : '0_') + e.code
    end
  end

  # POST /scans/return_labels
  def create
    if params[:return_labels] && params[:return_labels][:customers]
      @return_labels = ReturnLabels.new(params[:return_labels].merge(time: @current_time))
      @return_labels.render_pdf
    end
    redirect_to '/scans/return_labels'
  end
end

app/views/ppp/paper_set_orders/index.html.haml
#paper_set_orders.container-fluid
  .row.derivationLeft
    .col-md-10.text-start
      %h3.bold
        Liste des commandes de Kit Courriers
        %span.badge.badge-secondary.regular= @orders_count
    .col-md-2.text-center
      %button.btn.btn-light.semibold.ppp-filter.w-100
        %span.me-2 Filtrer
        %span= glyphicon('transfer', { size: '15', color: '#72AA42', style: 'transform: rotate(90deg)'})

  .mb-4

  .box.paper-set-orders-lst.derivationRight
    %table#paper-set-orders-tbl.table.table-condensed.table-striped.table-detachable-head.table-bordered-inner
      %thead
        %tr.text-grey
          %th= sortable :created_at, t('activerecord.models.common.attributes.created_at').downcase
          %th= sortable :id, 'n° cmde'
          %th= sortable :user_code, 'code'
          %th format
          %th période
          %th= sortable :state, t('activerecord.models.order.attributes.state').downcase
          %th= t('activerecord.models.paper_process.attributes.tracking_number').downcase
      %tbody
        - @orders.each do |order|
          %tr
            %td= l order.created_at, format: :standard
            %td= order.id
            %td= link_to "#{order.user_code}", organization_url(order.user.organization, tab: 'file_sending_kit')
            %td= order.paper_set_casing_size.to_s + 'g' + ' - ' + order.paper_set_folder_count.to_s + ' chemises'
            %td
              = paper_set_date_to_name(order.period_duration, order.paper_set_start_date)
              à
              = paper_set_date_to_name(order.period_duration, order.paper_set_end_date)
              \-
              = case order.period_duration
                - when 1 then 'Mensuel'
                - when 3 then 'Trimestriel'
                - when 12 then 'Annuel'
            %td= Order.state_machine.states[order.state].human_name
            %td= link_to_paper_tracking(order.kit) if order.kit.try(:tracking_number)

    = render file: Rails.root.join('app/views/shared/_pagination.html.haml'), locals: { url: paper_set_orders_path, filter: 'filter-documents-selection-form', target: '.paper-set-orders-lst', name: 'ppp-list-documents', mark: 'paper_set_orders', total_pages: @orders_count  }

.modal.fade.in#ppp-filter
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title.bold Filtre
        %button.btn-close{'aria-label' => 'Close', 'data-bs-dismiss' => 'modal', :type => 'button'}
      .modal-body
        %form#filter-documents-selection-form
          .form-group
            %label.semibold Date de création
            .select-container.no-padding.w-100
              %input.date.daterange{name: 'order_contains[created_at]', type: :text, value: params[:order_contains].try(:[], :created_at) }

          .form-group
            %label.semibold Code du dossier
            .select-container.no-padding.w-100
              %input#select-document{name: 'order_contains[user_code]', type: :text, value: params[:order_contains].try(:[], :user_code) }

          .form-group
            %label.semibold N° du suivi
            .select-container.no-padding.w-100.date
              %input{name: 'order_contains[tracking_number]', type: :text, value: params[:order_contains].try(:[], :tracking_number) }

          .form-group
            %label.semibold Statut :
            %select.form-select#state{name: 'order_contains[state]', value: params[:order_contains].try(:[], :state) }
              %option{value: ''}
              %option{value: 'confirmed'} Confirmé
              %option{value: 'processed' } Traitée

      .modal-footer
        - idocus_params = param_encode({ url: paper_set_orders_path, method: 'get', html: { target: '#paper_set_orders' }, modal: { id: 'ppp-filter' }, before_send: 'paper_set_order_reset_filter' })
        %button.btn.btn-light.semibold.as_idocus_ajax{ type: :button, idocus: idocus_params } Annuler
        - idocus_params = param_encode({ url: paper_set_orders_path, method: 'get', form: { id: 'filter-documents-selection-form' }, html: { target: '#paper_set_orders' }, modal: { id: 'ppp-filter' } })
        %button.btn.btn-primary.semibold.as_idocus_ajax{ type: :button, idocus: idocus_params } Valider