config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

class ActionDispatch::Routing::Mapper
  def front_draw(template)
    instance_eval(File.read(Rails.root.join("app/templates/front/#{template}/routes.rb")))
  end

  def back_draw(template)
    instance_eval(File.read(Rails.root.join("app/templates/back/#{template}/routes.rb")))
  end
end

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => redirect('/dashboard')
  get '/front/notifications/', controller: 'front/index', action: 'notifications'

  wash_out :dematbox

  devise_for :users

  authenticate :user, lambda { |u| u.is_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### ------------------------ front ---------------------------- ###
  get '/', to: redirect('/dashboard')
  front_draw('dashboard')
  front_draw('documentations')
  front_draw('notifications')
  front_draw('news')
  front_draw('account_number_rules')
  front_draw('account_sharings')
  front_draw('addresses')
  front_draw('bank_accounts')
  front_draw('bank_settings')
  front_draw('profiles')
  front_draw('collaborators')
  front_draw('compta_analytics')
  front_draw('exercises')
  front_draw('setups')
  front_draw('orders')
  front_draw('file_naming_policies')
  front_draw('knowings')
  front_draw('invoices')
  front_draw('reminder_emails')
  front_draw('file_sending_kits')
  front_draw('groups')
  front_draw('paper_set_orders')
  front_draw('journals')
  front_draw('ibiza')
  front_draw('my_company_files')
  front_draw('pack_reports')
  front_draw('accounting_plans')
  front_draw('vat_accounts')
  front_draw('csv_descriptors')
  front_draw('subscriptions')
  front_draw('group_organizations')
  front_draw('organizations')
  front_draw('preseizures')
  front_draw('documents')
  front_draw('documents_reloaded')
  front_draw('my_documents')
  front_draw('pieces_errors')
  front_draw('organizations')
  front_draw('reporting')
  front_draw('customers')
  front_draw('periods')
  front_draw('boxes')
  front_draw('external_file_storages')
  front_draw('ftps_setting')
  front_draw('payments')
  front_draw('compositions')
  front_draw('dematboxes')
  front_draw('retrievers')
  front_draw('retrieved_datas')
  front_draw('retrieved_datas_v2')
  front_draw('retriever_parameters')
  front_draw('exact_online')
  front_draw('paper_processes')
  front_draw('suspended')
  front_draw('profiles')
  front_draw('software_setting')
  front_draw('export_preseizures')

  ### --------------------------- admin ---------------------------- ###

  get 'admin/', to: redirect('/admin/dashboard')
  back_draw('dashboard')
  back_draw('reporting')
  back_draw('organizations')
  back_draw('process_reporting')
  back_draw('invoices')
  back_draw('users')
  back_draw('subscription_options')
  back_draw('subscriptions')
  back_draw('mobile_reporting')
  back_draw('orders')
  back_draw('events')
  back_draw('retrievers')
  back_draw('pre_assignment_deliveries')
  back_draw('dematboxes')
  back_draw('news')
  back_draw('emailed_documents')
  back_draw('cms_images')
  back_draw('scanning_providers')
  back_draw('account_sharings')
  back_draw('notifications')
  back_draw('pre_assignment_blocked_duplicates')
  back_draw('notification_settings')
  back_draw('job_processing')
  back_draw('counter_error_script_mailer')
  back_draw('budgea_retriever')
  back_draw('zoho_crms')
  back_draw('pkill')
  back_draw('reset')
  back_draw('package_setting')
  back_draw('tickets')
  back_draw('supports')

  #### -------------------------------- native resources -----------------------------###

  scope module: 'ppp' do
    resources :compta

    resources :kits, only: %w(index create)
    get 'kits/:year/:month/:day', controller: 'kits', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :receipts, only: %w(index create)
    get 'receipts/:year/:month/:day', controller: 'receipts', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :scans, only: %w(index create) do
      patch :add,       on: :member
      get   :cancel,    on: :collection
      patch :overwrite, on: :member
    end
    get 'scans/:year/:month/:day', controller: 'scans', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :returns, only: %w(index create)
    get 'returns/:year/:month/:day', controller: 'returns', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    scope '/scans' do
      resource :return_labels
    end
    post '/scans/return_labels/:year/:month/:day',     controller: 'return_labels', action: 'create'
    get  '/scans/return_labels/new/:year/:month/:day', controller: 'return_labels', action: 'new'

    get '/paper_set_orders', controller: 'paper_set_orders', action: 'index'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      resources :users, only: %w() do
        collection do
          get :jefacture
        end

        resources :accounting_plans,  only: %w(index)
        resources :account_book_types, only: %w(index)
      end

      resources :pieces,            only: %w(update)

      resources :operations,        only: %w(create) do
        get 'by_iban/:iban', action: 'index_by_iban', on: :collection
        post 'not_processed', action: 'not_processed', on: :collection
      end

      resources :temp_documents,    only: %w(create)

      resources :bank_accounts,     only: %w(index) do
        member do
          get :last_operation
        end
      end

      resources :neatops_specific, only: :create
    end

    namespace :v1 do
      resources :pre_assignments do
        post 'update_comment', on: :collection
      end

      resources :system, only: %w(index) do
        post 'my_customers', on: :collection
        post 'piece_url', on: :collection
      end
    end

    namespace :mobile do
      devise_for :users

      resources :remote_authentication do
        collection do
          post :request_connexion
          post :get_user_parameters
          post :ping
        end
      end

      resources :data_loader do
        collection do
          post :load_customers
          post :load_user_organizations
          post :load_packs
          post :load_documents_processed
          post :load_documents_processing
          post :load_stats
          post :load_preseizures
          post :get_packs
          post :get_reports
          get  :render_image_documents
        end
      end

      resources :preseizures do
        collection do
          post :get_details
          post :deliver
          post :edit_preseizures
          post :edit_account
          post :edit_entry
        end
      end

      resources :operations do
        collection do
          post :get_operations
          post :force_pre_assignment
          post :get_customers_options
        end
      end

      resources :account_sharing do
        collection do
          post :load_shared_docs
          post :load_shared_contacts

          post :get_list_collaborators
          post :get_list_customers
          post :add_shared_docs
          post :add_shared_contacts
          post :edit_shared_contacts
          post :accept_shared_docs
          post :delete_shared_docs
          post :delete_shared_contacts

          post :load_shared_docs_customers
          post :add_shared_docs_customers
          post :add_sharing_request_customers
        end
      end

      resources :file_uploader do
        post 'load_file_upload_params', on: :collection
        post 'load_file_upload_users', on: :collection
        post 'load_user_analytics', on: :collection
        post 'set_pieces_analytics', on: :collection
      end

      resources :firebase_notification do
        collection do
          post :get_notifications
          post :release_new_notifications
          post :register_firebase_token
        end
      end

      resources :error_report do
        post 'send_error_report', on: :collection
      end
    end

    namespace :sgi do
      namespace :v1 do
        resources :grouping do
          get 'bundle_needed/:delivery_type', action: 'bundle_needed',  on: :collection
          post 'bundled', on: :collection
        end

        resources :preassignment do
          get 'preassignment_needed/:compta_type', action: 'preassignment_needed', on: :collection
          get 'download_piece', on: :collection
          post 'push_preassignment/:piece_id', action: 'push_preassignment', on: :collection
          post 'update_teeo_pieces', action: 'update_teeo_pieces', on: :collection
        end

        resources :mapping_generator do
          get 'get_json', on: :collection
        end

        resources :jefacture do
          get 'waiting_validation',  on: :collection
          post 'pre_assigned',       on: :collection
        end
      end
    end
  end

  match '*a', to: 'errors#routing', via: :all
end

app/controllers/back_controller.rb
class BackController < ApplicationController
  before_action :login_user!
  before_action :verify_admin_rights

  layout ('back/layout')

  private

  def verify_admin_rights
    redirect_to root_url unless current_user.is_admin
  end
end

app/helpers/layouts_helper.rb
# -*- encoding : UTF-8 -*-
# FIXME : whole check

module LayoutsHelper
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of front/layouts/child.html.haml, include this:
  #
  # <% parent_layout "parent" %>
  #

  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "front/layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/back/_header_connexion.html.haml
.header-connexion.bg-white.derivationTop.readonly-trigger
  .row
    .col-md-9.user-name
      %h1.semibold
        = current_user.name
    .col-md-3.text-end
      %nav.navbar-expand-lg.navbar-light.ps-5
        %ul.nav.navbar-nav.w-100.pt-2.ps-5
          %li.nav-item.me-4.no-padding.no-hover
            %span.badge.rounded-pill.bg-secondary.regular.mt-2= current_user.email
          %li.nav-item.no-padding.no-hover
            = link_to glyphicon('fork', { size: 15, color:'rgba(26, 26, 26, 0.7)'} ), root_path, title: "Revenir à la page d'acceuil", class: 'nav-link', target: '_blank'    
          %li.nav-item.no-padding.no-hover
            = link_to glyphicon('power-standby', {size: 15, color: "red"}), destroy_user_session_path, method: :delete, class: 'nav-link', title: 'Déconnexion'

= javascript_declare_var 'is_super_admin', current_user.is_admin
= javascript_declare_var 'full_access', current_user.full_access

app/views/layouts/back/_lefter.html.haml
.lefter-content.side-menu
  .d-flex.flex-column.vh-100.flex-shrink-0.p-3.text-white.bg-dark
    .w-100.bg-white.head-logo.row
      .w-100
        = link_to image_tag('logo/tiny_logo_2.png', alt: 'logo iDocus', class: "w-100 ps-2"), '/', class: 'navbar-brand no-margin text-white text-decoration-none', data:{ href: '/' }
    %hr
    %ul.nav.nav-pills.flex-column.mb-auto
      %li.nav-item{ class: ('active' if controller_path == 'admin/dashboard/main') }
        = link_to(admin_dashboard_root_path) do
          %span.me-2= glyphicon('home', size: 12, color: "white")
          %span Tableau de bord
      %li.nav-item.dropdown{ class: ('active' if controller_path == 'admin/reporting/main' || controller_path == 'admin/process_reporting/main' || controller_path == 'admin/invoices/main' ) }
        = link_to '#', class: 'dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button" do
          %span.me-2= glyphicon('graph', size: 12, color: "white")
          %span Finance
          %span.float-end= glyphicon('chevron-right', size: 12, color: "white")
        .dropdown-menu.fadein
          = link_to '/admin/reporting', class: 'dropdown-item' do
            %span.me-2= glyphicon('calendar', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Reporting          
          = link_to '/admin/process_reporting', class: 'dropdown-item' do
            %span.me-2= glyphicon('grid-three-up', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Reporting de traitement          
          = link_to admin_invoices_index_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('document', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Factures
      %li.nav-item{ class: ('active' if controller_path == 'admin/organizations/main') }
        = link_to(admin_organizations_path) do
          %span.me-2= glyphicon('people', size: 12, color: "white")
          %span Organisations
      %li.nav-item{ class: ('active' if controller_path == 'admin/users/main') }
        = link_to(admin_users_path) do
          %span.me-2= glyphicon('person', size: 12, color: "white")
          %span Utilisateurs      
      %li.nav-item{ class: ('active' if controller_path == 'admin/subscription_options/main') }
        = link_to(admin_subscription_options_path) do
          %span.me-2= glyphicon('paperclip', size: 12, color: "white")
          %span Forfaits
      %li.nav-item.dropdown{ class: ('active' if controller_path == 'admin/pre_assignment_deliveries/main') } 
        = link_to '#', class: 'dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button" do
          %span.me-2= glyphicon('globe', size: 12, color: "white")
          %span Livraison pré-aff
          %span.float-end= glyphicon('chevron-right', size: 12, color: "white")
        .dropdown-menu.fadein        
          = link_to admin_pre_assignment_deliveries_path(software: 'ibiza'), class: 'dropdown-item' do
            %span.me-2= glyphicon('bold', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Vers Ibiza
          / = link_to admin_pre_assignment_deliveries_path(software: 'exact_online'), class: 'dropdown-item' do
          /   %span.me-2= glyphicon('british-pound', size: 12, color: "rgba(26, 26, 26, 0.7)")
          /   %span.text-dark Vers Exact Online          
          / = link_to admin_pre_assignment_deliveries_path(software: 'my_unisoft'), class: 'dropdown-item' do
          /   %span.me-2= glyphicon('audio-spectrum', size: 12, color: "rgba(26, 26, 26, 0.7)")
          /   %span.text-dark Vers My Unisoft
          = link_to admin_pre_assignment_deliveries_path(software: 'sage_gec'), class: 'dropdown-item' do
            %span.me-2= glyphicon('dollar', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Vers Sage GEC
      %li.nav-item.dropdown{ class: ('active' if controller_path == 'admin/subscriptions/main' || controller_path == 'admin/mobile_reporting/main') }
        = link_to '#', class: 'dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button" do
          %span.me-2= glyphicon('pie-chart', size: 12, color: "white")
          %span Statistiques
          %span.float-end= glyphicon('chevron-right', size: 12, color: "white")
        .dropdown-menu.fadein
          = link_to admin_subscriptions_index_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('calendar', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Reporting          
          = link_to admin_mobile_reporting_index_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('grid-three-up', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Reporting Mobile
      %li.nav-item.dropdown{ class: ('active' if controller_path == 'admin/dematboxes/main' || controller_path == 'admin/dematboxes/services' || controller_path == 'admin/dematboxes/files') } 
        = link_to '#', class: 'dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button" do
          %span.me-2= glyphicon('book', size: 12, color: "white")
          %span iDocus'Box
          %span.float-end= glyphicon('chevron-right', size: 12, color: "white")
        .dropdown-menu.fadein
          = link_to admin_dematboxes_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('calendar', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Dematbox          
          = link_to admin_dematbox_services_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('grid-three-up', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Services & Groupes
          = link_to admin_dematbox_files_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('grid-three-up', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Fichiers
      %li.nav-item{ class: ('active' if controller_path == 'admin/orders/main') }
        = link_to(admin_orders_index_path) do
          %span.me-2= glyphicon('aperture', size: 12, color: "white")
          %span Commandes
      %li.nav-item{ class: ('active' if controller_path == 'admin/events/main') }
        = link_to(admin_events_path) do
          %span.me-2= glyphicon('target', size: 12, color: "white")
          %span Visites      
      %li.nav-item{ class: ('active' if controller_path == 'admin/retrievers/main') }
        = link_to admin_retrievers_path, class: 'dropdown-item' do
          %span.me-2= glyphicon('calendar', size: 12, color: "rgba(26, 26, 26, 0.7)")
          %span.text-dark Automates
      %li.nav-item{ class: ('active' if controller_path == 'admin/tickets/main') }
        = link_to admin_tickets_path do
          %span.me-2= glyphicon('print', size: 12, color: "white")
          %span Tickets informatiques

    %hr
      %li.nav-item{ class: ('active' if controller_path == 'admin/support/main') }
        = link_to admin_supports_path do
          %span.me-2= glyphicon('print', size: 12, color: "white")
          %span Support-Tech
      %li.nav-item.dropdown{ class: ('active' if ['admin/news/main', 'admin/emailed_documents/main', 'admin/cms_images/main', 'admin/scanning_providers/main', 'admin/account_sharings/main', 'admin/notifications/main', 'admin/pre_assignment_blocked_duplicates/main', 'admin/notification_settings/main', 'admin/zoho_crms/main'].include?controller_path ) } 
        = link_to '#', class: 'dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button" do
          %span.me-2= glyphicon('signal', size: 12, color: "white")
          %span Autres
          %span.float-end= glyphicon('chevron-right', size: 12, color: "white")
        .dropdown-menu.fadein         
          = link_to admin_news_index_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('tablet', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark News
          = link_to admin_emailed_documents_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('envelope-closed', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Récéptions Mail
          = link_to admin_cms_images_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('puzzle-piece', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Images
          = link_to admin_scanning_providers_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('location', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Ateliers
          = link_to admin_account_sharings_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('share', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Partages de compte
          = link_to admin_notifications_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('bell', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Notifications utilisateurs
          = link_to admin_pre_assignment_blocked_duplicates_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('double-quote-sans-left', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Doublons pré-aff
          = link_to admin_notification_settings_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('cog', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Paramétrage notifications
          = link_to admin_zoho_crms_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('star', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Synchronization Zoho Crm
      %li.nav-item.dropdown{ class: ('active' if ['admin/job_processing/main', 'admin/budgea_retriever/main', 'admin/counter_error_script_mailer/main', 'admin/pkill/main', 'admin/reset/main', 'admin/retrievers/main', 'admin/package_setting/main'].include?controller_path ) } 
        = link_to '#', class: 'dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button" do
          %span.me-2= glyphicon('code', size: 12, color: "white")
          %span Outils DEV
          %span.float-end= glyphicon('chevron-right', size: 12, color: "white")
        .dropdown-menu.fadein
          - if current_user.is_developer     
            = link_to admin_job_processing_index_path, class: 'dropdown-item' do
              %span.me-2= glyphicon('sun', size: 12, color: "rgba(26, 26, 26, 0.7)")
              %span.text-dark Suivi Job Process
            = link_to admin_budgea_retriever_index_path, class: 'dropdown-item' do
              %span.me-2= glyphicon('timer', size: 12, color: "rgba(26, 26, 26, 0.7)")
              %span.text-dark Suivi Retriever Budgea
            = link_to admin_counter_error_script_mailer_index_path, class: 'dropdown-item' do
              %span.me-2= glyphicon('bug', size: 12, color: "rgba(26, 26, 26, 0.7)")
              %span.text-dark Suivi Error Script Mailer
            = link_to admin_pkill_index_path, class: 'dropdown-item' do
              %span.me-2= glyphicon('media-stop', size: 12, color: "rgba(26, 26, 26, 0.7)")
              %span.text-dark Pkill process
            = link_to admin_reset_index_path, class: 'dropdown-item' do
              %span.me-2= glyphicon('fire', size: 12, color: "rgba(26, 26, 26, 0.7)")
              %span.text-dark Reset Page            
          = link_to fetcher_admin_retrievers_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('script', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark Récup. transactions
          = link_to admin_package_setting_index_path, class: 'dropdown-item' do
            %span.me-2= glyphicon('badge', size: 12, color: "rgba(26, 26, 26, 0.7)")
            %span.text-dark iDo premium


            

app/views/layouts/back/_messages.html.haml
.back-notice-flush
  - flash.each do |name, msg|
    %div{ class: "alert alert-#{['notice', 'success'].include?(name) ? 'success' : 'danger'}" }
      %a.close{ "data-dismiss" => "alert" } x
      != content_tag :div, msg, { :id => "flash_#{name}" }, false if msg.is_a?(String)

app/views/layouts/back/layout.html.haml
!!!
%html
  %head
    %title
      - if content_for?(:title)
        = yield(:title)
      - else
        Idocus | Archivage numérique
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-type" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    = yield(:head)

    %link{ :rel => 'shortcut icon', :type => "image/ico", :href => image_path('favicon.ico') }
    = csrf_meta_tag
    = stylesheet_link_tag 'admin'
    = javascript_include_tag Ckeditor.cdn_url
    = javascript_include_tag 'back/main'

    :plain
      <!--[if lt IE 9]>
        <script src="/assets/html5.js" type="text/javascript"></script>
      <![endif]-->

  .row
    .col-md-2.lefter-dark.no-padding
      = render 'layouts/back/lefter'
    .col-md-10.no-padding
      = render 'layouts/back/header_connexion'  
      .body_content{ style: "height: 900px;" }
        = yield
        .push

      .scroll-on-top.pointer.hide
        .scroll-arrow= glyphicon('chevron-top', { size: '16', color: 'white' })

      = render partial: 'layouts/back/messages'

      %footer.fixed-bottom.footer.clearfix
        %p.copyright{ style: 'text-align:center;' } &copy; iDocus #{Time.now.year}

  .loading_box.hide
    .box.text-center
      %img{ src: '/assets/application/spinner_gray_alpha.gif', alt: 'spin gif'}
      %label.mt-2.semibold Chargement

  .scroll-on-top.pointer.hide
    .scroll-arrow= glyphicon('chevron-top', { size: '16', color: 'white' })