config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

class ActionDispatch::Routing::Mapper
  def front_draw(template)
    instance_eval(File.read(Rails.root.join("app/templates/front/#{template}/routes.rb")))
  end

  def back_draw(template)
    instance_eval(File.read(Rails.root.join("app/templates/back/#{template}/routes.rb")))
  end
end

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => redirect('/dashboard')
  get '/front/notifications/', controller: 'front/index', action: 'notifications'

  wash_out :dematbox

  devise_for :users

  authenticate :user, lambda { |u| u.is_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### ------------------------ front ---------------------------- ###
  get '/', to: redirect('/dashboard')
  front_draw('dashboard')
  front_draw('documentations')
  front_draw('notifications')
  front_draw('news')
  front_draw('account_number_rules')
  front_draw('account_sharings')
  front_draw('addresses')
  front_draw('bank_accounts')
  front_draw('bank_settings')
  front_draw('profiles')
  front_draw('collaborators')
  front_draw('compta_analytics')
  front_draw('exercises')
  front_draw('setups')
  front_draw('orders')
  front_draw('file_naming_policies')
  front_draw('knowings')
  front_draw('invoices')
  front_draw('reminder_emails')
  front_draw('file_sending_kits')
  front_draw('groups')
  front_draw('paper_set_orders')
  front_draw('journals')
  front_draw('ibiza')
  front_draw('my_company_files')
  front_draw('pack_reports')
  front_draw('accounting_plans')
  front_draw('vat_accounts')
  front_draw('csv_descriptors')
  front_draw('subscriptions')
  front_draw('group_organizations')
  front_draw('organizations')
  front_draw('preseizures')
  front_draw('documents')
  front_draw('documents_reloaded')
  front_draw('my_documents')
  front_draw('pieces_errors')
  front_draw('organizations')
  front_draw('reporting')
  front_draw('customers')
  front_draw('periods')
  front_draw('boxes')
  front_draw('external_file_storages')
  front_draw('ftps_setting')
  front_draw('payments')
  front_draw('compositions')
  front_draw('dematboxes')
  front_draw('retrievers')
  front_draw('retrieved_datas')
  front_draw('retrieved_datas_v2')
  front_draw('retriever_parameters')
  front_draw('exact_online')
  front_draw('paper_processes')
  front_draw('suspended')
  front_draw('profiles')
  front_draw('software_setting')
  front_draw('export_preseizures')

  ### --------------------------- admin ---------------------------- ###

  get 'admin/', to: redirect('/admin/dashboard')
  back_draw('dashboard')
  back_draw('reporting')
  back_draw('organizations')
  back_draw('process_reporting')
  back_draw('invoices')
  back_draw('users')
  back_draw('subscription_options')
  back_draw('subscriptions')
  back_draw('mobile_reporting')
  back_draw('orders')
  back_draw('events')
  back_draw('retrievers')
  back_draw('pre_assignment_deliveries')
  back_draw('dematboxes')
  back_draw('news')
  back_draw('emailed_documents')
  back_draw('cms_images')
  back_draw('scanning_providers')
  back_draw('account_sharings')
  back_draw('notifications')
  back_draw('pre_assignment_blocked_duplicates')
  back_draw('notification_settings')
  back_draw('job_processing')
  back_draw('counter_error_script_mailer')
  back_draw('budgea_retriever')
  back_draw('zoho_crms')
  back_draw('pkill')
  back_draw('reset')
  back_draw('package_setting')
  back_draw('tickets')
  back_draw('supports')

  #### -------------------------------- native resources -----------------------------###

  scope module: 'ppp' do
    resources :compta

    resources :kits, only: %w(index create)
    get 'kits/:year/:month/:day', controller: 'kits', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :receipts, only: %w(index create)
    get 'receipts/:year/:month/:day', controller: 'receipts', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :scans, only: %w(index create) do
      patch :add,       on: :member
      get   :cancel,    on: :collection
      patch :overwrite, on: :member
    end
    get 'scans/:year/:month/:day', controller: 'scans', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    resources :returns, only: %w(index create)
    get 'returns/:year/:month/:day', controller: 'returns', action: 'index', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }


    scope '/scans' do
      resource :return_labels
    end
    post '/scans/return_labels/:year/:month/:day',     controller: 'return_labels', action: 'create'
    get  '/scans/return_labels/new/:year/:month/:day', controller: 'return_labels', action: 'new'

    get '/paper_set_orders', controller: 'paper_set_orders', action: 'index'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      resources :users, only: %w() do
        collection do
          get :jefacture
        end

        resources :accounting_plans,  only: %w(index)
        resources :account_book_types, only: %w(index)
      end

      resources :pieces,            only: %w(update)

      resources :operations,        only: %w(create) do
        get 'by_iban/:iban', action: 'index_by_iban', on: :collection
        post 'not_processed', action: 'not_processed', on: :collection
      end

      resources :temp_documents,    only: %w(create)

      resources :bank_accounts,     only: %w(index) do
        member do
          get :last_operation
        end
      end

      resources :neatops_specific, only: :create
    end

    namespace :v1 do
      resources :pre_assignments do
        post 'update_comment', on: :collection
      end

      resources :system, only: %w(index) do
        post 'my_customers', on: :collection
        post 'piece_url', on: :collection
      end
    end

    namespace :mobile do
      devise_for :users

      resources :remote_authentication do
        collection do
          post :request_connexion
          post :get_user_parameters
          post :ping
        end
      end

      resources :data_loader do
        collection do
          post :load_customers
          post :load_user_organizations
          post :load_packs
          post :load_documents_processed
          post :load_documents_processing
          post :load_stats
          post :load_preseizures
          post :get_packs
          post :get_reports
          get  :render_image_documents
        end
      end

      resources :preseizures do
        collection do
          post :get_details
          post :deliver
          post :edit_preseizures
          post :edit_account
          post :edit_entry
        end
      end

      resources :operations do
        collection do
          post :get_operations
          post :force_pre_assignment
          post :get_customers_options
        end
      end

      resources :account_sharing do
        collection do
          post :load_shared_docs
          post :load_shared_contacts

          post :get_list_collaborators
          post :get_list_customers
          post :add_shared_docs
          post :add_shared_contacts
          post :edit_shared_contacts
          post :accept_shared_docs
          post :delete_shared_docs
          post :delete_shared_contacts

          post :load_shared_docs_customers
          post :add_shared_docs_customers
          post :add_sharing_request_customers
        end
      end

      resources :file_uploader do
        post 'load_file_upload_params', on: :collection
        post 'load_file_upload_users', on: :collection
        post 'load_user_analytics', on: :collection
        post 'set_pieces_analytics', on: :collection
      end

      resources :firebase_notification do
        collection do
          post :get_notifications
          post :release_new_notifications
          post :register_firebase_token
        end
      end

      resources :error_report do
        post 'send_error_report', on: :collection
      end
    end

    namespace :sgi do
      namespace :v1 do
        resources :grouping do
          get 'bundle_needed/:delivery_type', action: 'bundle_needed',  on: :collection
          post 'bundled', on: :collection
        end

        resources :preassignment do
          get 'preassignment_needed/:compta_type', action: 'preassignment_needed', on: :collection
          get 'download_piece', on: :collection
          post 'push_preassignment/:piece_id', action: 'push_preassignment', on: :collection
          post 'update_teeo_pieces', action: 'update_teeo_pieces', on: :collection
        end

        resources :mapping_generator do
          get 'get_json', on: :collection
        end

        resources :jefacture do
          get 'waiting_validation',  on: :collection
          post 'pre_assigned',       on: :collection
        end
      end
    end
  end

  match '*a', to: 'errors#routing', via: :all
end

app/controllers/front/index_controller.rb
# frozen_string_literal: true

class Front::IndexController < ApplicationController
  before_action :load_user_and_role
  before_action :verify_suspension
  before_action :verify_if_active

  def index
    render 'layouts/front/layout'
  end

  def notifications
    @notifications = []

    4.times do |i|
      test_notif = FakeObject.new()
      test_notif.id = i + 1
      test_notif.title = '1 erreur détéctée'
      test_notif.date = i.days.ago
      test_notif.content = "IDOC%001 : blabla bla notification N°#{i}"

      @notifications << test_notif
    end

    render 'layouts/front/notifications'
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  XHR_TOKEN  = 'dHkgbnkgdG9rZW4gYW5sZSBhamF4'
  before_action :login_user!
  before_action :load_user_and_role
  before_action :verify_suspension
  before_action :verify_if_active
  # before_action :check_xhr_token


  layout :define_layout

  def check_xhr_token
    xhr_token = params[:xhr_token].to_s
    path      = request.path.to_s

    if xhr_token != FrontController::XHR_TOKEN && path != '/'
      next_path = Base64.encode64 path
      redirect_to "#{root_path}?r=#{next_path}"
    end
  end

  protected

  def load_user_and_role(name = :@user)
    super do |collaborator|
      if params[:organization_id].present?
        organization = collaborator.organizations.find(params[:organization_id])
        collaborator.with_organization_scope(organization)
      end
    end
  end

  def define_layout
    if request.env["SERVER_NAME"].include?("axelium")
      'front/layout_axelium'
    elsif request.env["SERVER_NAME"].include?('dkpartners')
      'front/layout_dk_partners'
    elsif request.env["SERVER_NAME"].include?('censial')
      'front/layout_censial'
    elsif request.env["SERVER_NAME"].include?('orial')
      'front/layout_orial'
    else
      'front/layout'
    end
  end
end

app/helpers/layouts_helper.rb
# -*- encoding : UTF-8 -*-
# FIXME : whole check

module LayoutsHelper
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of front/layouts/child.html.haml, include this:
  #
  # <% parent_layout "parent" %>
  #

  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "front/layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/front/_header_axelium.html.haml
= javascript_declare_var 'controller_path', controller_path

%nav.navbar.navbar-expand-lg.fixed-top.main_menu
  .row.w-100.no-margin
    .col-md-1.text-center.content-logo
      = link_to image_tag('logo/tiny_logo_axelium.png', alt: 'logo Axelium'), '/', class: 'navbar-brand no-margin', data:{ href: '/' }
    .col-md-9.menu
      %ul.navbar-nav
        %li.nav-item{ class: (controller_path == 'dashboard/main')? 'active' : '' }
          =link_to t('layouts.home'), '/', class: 'nav-link goto_button bold', data:{ href: '/' }
        - unless organizations_suspended? && @user.active? 
          - is_document_active = controller_path == 'documents/pieces' || controller_path == 'pieces_errors/main'
          %li.nav-item.dropdown{ class: (is_document_active)? 'active' : '' }
            =link_to t('layouts.my_documents'), '', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenudocuments', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button"
            .dropdown-menu.semibold{"aria-labelledby" => "navbardropdownmenudocuments"}
              =link_to t('layouts.pieces_and_pre_assignment'), documents_path, class: (controller_path == 'documents/pieces')? 'dropdown-item active' : 'dropdown-item'
              =link_to t('layouts.pieces_errors'), pieces_errors_path, class: (controller_path == 'pieces_errors/main')? 'dropdown-item active' : 'dropdown-item'
          %li.nav-item{ class: (controller_path == 'documents/operations')? 'active' : '' }
            =link_to t('layouts.bank_operations'), operations_path, class: 'nav-link bold'

        - if @user.collaborator?
          - if @user.has_one_organization?
            - if @user.inactive? || @user.organizations_not_suspended? || @user.can_unsuspend?
              - path = (organizations_suspended? && @user.active?) ? edit_payment_organization_path(@user.organization) : organization_path(@user.organization)
              %li.nav-item{ class: (controller_path == 'organizations/main')? 'active' : '' }
                =link_to t('layouts.my_company'), path, class: 'nav-link bold'
            - if @user.active? && @user.organization.is_active
              %li.nav-item{ class: (controller_path == 'reporting/main')? 'active' : '' }
                =link_to t('layouts.reporting'), "/reporting/#{@user.organization.try(:id)}", class: 'nav-link bold'
          - elsif @user.organizations_not_suspended? || @user.can_unsuspend?
            %li.nav-item.dropdown{ class: (controller_path == 'organizations/main')? 'active' : '' }
              =link_to t('layouts.my_company'), '', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenucompany', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button"
              .dropdown-menu.semibold{"aria-labelledby" => "navbardropdownmenucompany"}
                - @user.organizations.each do |organization|
                  - if organization.is_suspended
                    = link_to edit_payment_organization_path(organization), class: (organization.id == @organization.try(:id))? 'dropdown-item active' : 'dropdown-item' do
                      = organization.name
                      %i (Suspendu)
                  - else
                    = link_to organization.name, organization_path(organization), class: (organization.id == @organization.try(:id))? 'dropdown-item active' : 'dropdown-item'
            %li.nav-item.dropdown{ class: (controller_path == 'reporting/main')? 'active' : '' }
              =link_to t('layouts.reporting'), '', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenureporting', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button"
              .dropdown-menu.semibold{"aria-labelledby" => "navbardropdownmenureporting"}
                - @user.organizations.each do |organization|
                  - if organization.is_suspended
                    = link_to reporting_statistics_index_path(organization_id: organization.id), class: (organization.id == @organization.try(:id))? 'dropdown-item active' : 'dropdown-item' do
                      = organization.name
                      %i (Suspendu)
                  - else
                    = link_to organization.name, reporting_statistics_index_path(organization_id: organization.id), class: (organization.id == @organization.try(:id))? 'dropdown-item active' : 'dropdown-item'
        - if accounts.detect { |e| e.my_package.try(:bank_active) } || @user.organization.specific_mission
          - is_retriever_active = controller_path == 'retrievers/main' || controller_path == 'retrieved_datas/main' || controller_path == 'retriever_parameters/main'
          %li.nav-item.dropdown{ class: (is_retriever_active)? 'active' : '' }
            =link_to t('layouts.my_retrievers'), '', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenuretriever', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button"
            .dropdown-menu.semibold{"aria-labelledby" => "navbardropdownmenuretriever"}
              =link_to t('layouts.retriever.automates'), retrievers_path, class: (controller_path == 'retrievers/main')? 'dropdown-item active' : 'dropdown-item'
              =link_to t('layouts.retriever.historic'), retrievers_historics_path, class: (controller_path == 'retrieved_datas/main')? 'dropdown-item active' : 'dropdown-item'
              =link_to t('layouts.retriever.parameters'), retriever_parameters_path, class: (controller_path == 'retriever_parameters/main')? 'dropdown-item active' : 'dropdown-item'

    .col-md-2.user-menu
      %ul.navbar-nav.float-end
        - if Rails.env != 'production'
          %li.nav-item.me-4
            %span.badge.rounded-pill.bg-light.text-dark.regular.mt-2=  Rails.env
        - if current_user.try(:is_admin)
          %li.nav-item
            =link_to glyphicon('fork', color: "rgba(26, 26, 26, 0.7);", size: '22'), '/admin', class: 'nav-link bold'
          - if session[:user_code].presence
            %li.nav-item
              %span.badge.rounded-pill.badge-warning.semibold.mt-2= current_user_info        
          %li.nav-item
            =link_to glyphicon('people', color: "rgba(26, 26, 26, 0.7);", size: '22'), '#', class: 'nav-link bold me-1 as_user position-relative'

        %li.nav-item.dropdown
          %span#notification_count.badge.badge-alert.fs-origin.float-end.notif-badge.semibold
          = link_to glyphicon('bell', color: "rgba(26, 26, 26, 0.7);", size: '22'), '#notification', class: 'nav-link dropdown-toggle', id: 'notification-content', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => 'dropdown'
          .dropdown-menu.dropdown-menu-end.notification-content-list.no-padding.box{"aria-labelledby" => "notification-content"}
            = render file: Rails.root.join('app/templates/front/notifications/views/notifications/_notifier.html.haml')

        %li.nav-item.dropdown
          = link_to glyphicon('cog', color: "rgba(26, 26, 26, 0.7);", size: '22'), '#configure-profile', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenusetting', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => 'dropdown'
          .dropdown-menu.dropdown-menu-end.semibold.box.parameters_notifications{"aria-labelledby" => "navbardropdownmenusetting"}
            = link_to glyphicon('person', {size: '13', color: '#212529'}) + ' Mon compte', '/profiles', class: 'dropdown-item', target: '_blank'

            - if @user.pre_assignement_displayed?
              = link_to glyphicon('comment-square', {size: '13', color: '#212529'}) + " Centre d'aide", 'https://idocus.zendesk.com/hc/fr', class: 'dropdown-item', target: '_blank'
            -else
              = link_to glyphicon('document', {size: '13', color: '#212529'}) + " Documentation", download_document_path(name: 'doc_final_users_axelium.pdf'), class: 'dropdown-item', target: '_blank'

            = link_to glyphicon('power-standby', {size: '13', color: '#FF4848'}) + ' Se déconnecter', destroy_user_session_path, method: 'delete', class: 'dropdown-item red-label account-log-out'

app/views/layouts/front/_header_censial.html.haml
= javascript_declare_var 'controller_path', controller_path

%nav.navbar.navbar-expand-lg.fixed-top.main_menu
  .row.w-100.no-margin
    .col-md-1.text-center.content-logo
      = link_to image_tag('logo/tiny_logo_censial.png', alt: 'logo Censial Online'), '/', class: 'navbar-brand no-margin', data:{ href: '/' }
    .col-md-9.menu
      %ul.navbar-nav
        %li.nav-item{ class: (controller_path == 'dashboard/main')? 'active' : '' }
          =link_to t('layouts.home'), '/', class: 'nav-link goto_button bold', data:{ href: '/' }
        - unless organizations_suspended? && @user.active? 
          - is_document_active = controller_path == 'documents/pieces' || controller_path == 'pieces_errors/main'
          %li.nav-item.dropdown{ class: (is_document_active)? 'active' : '' }
            =link_to t('layouts.my_documents'), '', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenudocuments', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button"
            .dropdown-menu.semibold{"aria-labelledby" => "navbardropdownmenudocuments"}
              =link_to t('layouts.pieces_and_pre_assignment'), documents_path, class: (controller_path == 'documents/pieces')? 'dropdown-item active' : 'dropdown-item'
              =link_to t('layouts.pieces_errors'), pieces_errors_path, class: (controller_path == 'pieces_errors/main')? 'dropdown-item active' : 'dropdown-item'
          %li.nav-item{ class: (controller_path == 'documents/operations')? 'active' : '' }
            =link_to t('layouts.bank_operations'), operations_path, class: 'nav-link bold'

        - if @user.collaborator?
          - if @user.has_one_organization?
            - if @user.inactive? || @user.organizations_not_suspended? || @user.can_unsuspend?
              - path = (organizations_suspended? && @user.active?) ? edit_payment_organization_path(@user.organization) : organization_path(@user.organization)
              %li.nav-item{ class: (controller_path == 'organizations/main')? 'active' : '' }
                =link_to t('layouts.my_company'), path, class: 'nav-link bold'
            - if @user.active? && @user.organization.is_active
              %li.nav-item{ class: (controller_path == 'reporting/main')? 'active' : '' }
                =link_to t('layouts.reporting'), "/reporting/#{@user.organization.try(:id)}", class: 'nav-link bold'
          - elsif @user.organizations_not_suspended? || @user.can_unsuspend?
            %li.nav-item.dropdown{ class: (controller_path == 'organizations/main')? 'active' : '' }
              =link_to t('layouts.my_company'), '', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenucompany', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button"
              .dropdown-menu.semibold{"aria-labelledby" => "navbardropdownmenucompany"}
                - @user.organizations.each do |organization|
                  - if organization.is_suspended
                    = link_to edit_payment_organization_path(organization), class: (organization.id == @organization.try(:id))? 'dropdown-item active' : 'dropdown-item' do
                      = organization.name
                      %i (Suspendu)
                  - else
                    = link_to organization.name, organization_path(organization), class: (organization.id == @organization.try(:id))? 'dropdown-item active' : 'dropdown-item'
            %li.nav-item.dropdown{ class: (controller_path == 'reporting/main')? 'active' : '' }
              =link_to t('layouts.reporting'), '', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenureporting', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button"
              .dropdown-menu.semibold{"aria-labelledby" => "navbardropdownmenureporting"}
                - @user.organizations.each do |organization|
                  - if organization.is_suspended
                    = link_to reporting_statistics_index_path(organization_id: organization.id), class: (organization.id == @organization.try(:id))? 'dropdown-item active' : 'dropdown-item' do
                      = organization.name
                      %i (Suspendu)
                  - else
                    = link_to organization.name, reporting_statistics_index_path(organization_id: organization.id), class: (organization.id == @organization.try(:id))? 'dropdown-item active' : 'dropdown-item'
        - if accounts.detect { |e| e.my_package.try(:bank_active) } || @user.organization.specific_mission
          - is_retriever_active = controller_path == 'retrievers/main' || controller_path == 'retrieved_datas/main' || controller_path == 'retriever_parameters/main'
          %li.nav-item.dropdown{ class: (is_retriever_active)? 'active' : '' }
            =link_to t('layouts.my_retrievers'), '', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenuretriever', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => "dropdown", 'role' => "button"
            .dropdown-menu.semibold{"aria-labelledby" => "navbardropdownmenuretriever"}
              =link_to t('layouts.retriever.automates'), retrievers_path, class: (controller_path == 'retrievers/main')? 'dropdown-item active' : 'dropdown-item'
              =link_to t('layouts.retriever.historic'), retrievers_historics_path, class: (controller_path == 'retrieved_datas/main')? 'dropdown-item active' : 'dropdown-item'
              =link_to t('layouts.retriever.parameters'), retriever_parameters_path, class: (controller_path == 'retriever_parameters/main')? 'dropdown-item active' : 'dropdown-item'

    .col-md-2.user-menu
      %ul.navbar-nav.float-end
        - if Rails.env != 'production'
          %li.nav-item.me-4
            %span.badge.rounded-pill.bg-light.text-dark.regular.mt-2=  Rails.env
        - if current_user.try(:is_admin)
          %li.nav-item
            =link_to glyphicon('fork', color: "rgba(26, 26, 26, 0.7);", size: '22'), '/admin', class: 'nav-link bold'
          - if session[:user_code].presence
            %li.nav-item
              %span.badge.rounded-pill.badge-warning.semibold.mt-2= current_user_info        
          %li.nav-item
            =link_to glyphicon('people', color: "rgba(26, 26, 26, 0.7);", size: '22'), '#', class: 'nav-link bold me-1 as_user position-relative'

        %li.nav-item.dropdown
          %span#notification_count.badge.badge-alert.fs-origin.float-end.notif-badge.semibold
          = link_to glyphicon('bell', color: "rgba(26, 26, 26, 0.7);", size: '22'), '#notification', class: 'nav-link dropdown-toggle', id: 'notification-content', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => 'dropdown'
          .dropdown-menu.dropdown-menu-end.notification-content-list.no-padding.box{"aria-labelledby" => "notification-content"}
            = render file: Rails.root.join('app/templates/front/notifications/views/notifications/_notifier.html.haml')

        %li.nav-item.dropdown
          = link_to glyphicon('cog', color: "rgba(26, 26, 26, 0.7);", size: '22'), '#configure-profile', class: 'nav-link dropdown-toggle bold', id: 'navbardropdownmenusetting', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => 'dropdown'
          .dropdown-menu.dropdown-menu-end.semibold.box.parameters_notifications{"aria-labelledby" => "navbardropdownmenusetting"}
            = link_to glyphicon('person', {size: '13', color: '#212529'}) + ' Mon compte', '/profiles', class: 'dropdown-item', target: '_blank'

            - if @user.pre_assignement_displayed?
              = link_to glyphicon('comment-square', {size: '13', color: '#212529'}) + " Centre d'aide", 'https://idocus.zendesk.com/hc/fr', class: 'dropdown-item', target: '_blank'
            -else
              = link_to glyphicon('document', {size: '13', color: '#212529'}) + " Documentation", download_document_path(name: 'doc_final_users_censial.pdf'), class: 'dropdown-item', target: '_blank'

            = link_to glyphicon('power-standby', {size: '13', color: '#FF4848'}) + ' Se déconnecter', destroy_user_session_path, method: 'delete', class: 'dropdown-item red-label account-log-out'

app/views/layouts/front/_main_modal.html.haml
.modal.fade.in#general_idocus_main_modal
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title.bold
        %button.btn-close{ 'aria-label' => 'Close', 'data-bs-dismiss' => 'modal', :type => 'button' }
      .modal-body
      .modal-footer
        %button.btn.btn-primary.template.hide
        %button.btn.btn-light.cancel.hide{ 'aria-label' => 'Close', 'data-bs-dismiss' => 'modal', :type => 'button' } Annuler
        .appendable_elements